FROM cyberdojofoundation/javascript-node
LABEL maintainer=jon@jaggersoft.com

RUN npm install -global qunit qunit-cli chai sinon sinon-chai

ENV NODE_PATH /usr/lib/node_modules

COPY red_amber_green.rb /usr/local/bin
